### ISSUE TITLE
Add preview image in readme

### ISSUE THREAD

**Issue by riccardoscalco** [nextbitlabs/Rapido#23]

**Comment by aayushbisen** [comment]
Did you mean preview image of website?

**Comment by riccardoscalco** [comment]
Yes, I mean a preview image of the documentation page.

I think that looking at this issue is premature, so I am not going to accept any PR for the moment.
I am still not convinced it is a good idea having a preview of the documentation, for sure I do not want to pass the idea that Rapido is an application that one can install.
