### ISSUE TITLE
add 2018 Nobel peace prize

### ISSUE THREAD

**Issue by riccardoscalco** [nextbitlabs/Rapido#38]

**Comment by aayushbisen** [comment]
Can you please elaborate more on this issue?

**Comment by riccardoscalco** [comment]
Sure. In section **Table**, in the documentation (file `index.html`), the example is a table with the latest Nobel peace prices. The table is not updated, therefore the issue. Note that we took data from [wikipedia](https://en.wikipedia.org/wiki/List_of_Nobel_Peace_Prize_laureates).

**Comment by aayushbisen** [comment]
Thank you @riccardoscalco . I have added the 2018 Noble Peace Prize laureates

**Comment by riccardoscalco** [comment]
Closed with https://github.com/nextbitlabs/Rapido/pull/43.
